version: "3.7"

services:

  api:
    build:
      context: .
    image: {{projectName}}
    container_name: {{projectName}}-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
{{#hasDepends}}
    depends_on:
{{/hasDepends}}
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - amqp
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - internal

  greeter:
    build:
      context: .
    image: {{projectName}}
    container_name: {{projectName}}-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    labels:
      - "traefik.enable=false"
{{#hasDepends}}
    depends_on:
{{/hasDepends}}
{{#if_eq transporter "NATS"}}
      - nats
{{/if_eq}}
{{#redis}}
      - redis
{{/redis}}
{{#if_eq transporter "MQTT"}}
      - mqtt
{{/if_eq}}
{{#if_eq transporter "AMQP"}}
      - amqp
{{/if_eq}}
{{#if_eq transporter "STAN"}}
      - stan
{{/if_eq}}
{{#if_eq transporter "Kafka"}}
      - zookeeper
{{/if_eq}}

{{#if_eq transporter "NATS"}}
  networks:
    - internal

  nats:
    image: nats
    labels:
      - "traefik.enable=false"
    networks:
      - internal
{{/if_eq}}
{{#redis}}

  redis:
    image: redis:alpine
    labels:
      - "traefik.enable=false"
    networks:
      - internal
{{/redis}}
{{#if_eq transporter "MQTT"}}

  mqtt:
    image: ncarlier/mqtt
    labels:
      - "traefik.enable=false"
    networks:
      - internal
{{/if_eq}}
{{#if_eq transporter "AMQP"}}

  amqp:
    image: rabbitmq:3
    labels:
      - "traefik.enable=false"
    networks:
      - internal
{{/if_eq}}
{{#if_eq transporter "STAN"}}

  stan:
    image: nats-streaming
    labels:
      - "traefik.enable=false"
{{/if_eq}}
{{#if_eq transporter "Kafka"}}

  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    labels:
      - "traefik.enable=false"
    depends_on:
      - zookeeper
    networks:
      - internal
{{/if_eq}}

  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - internal
      - default

networks:
  internal:
