name: Test template

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        transporter: [NATS, Redis, MQTT, AMQP, STAN, Kafka]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} with ${{ matrix.transporter }} transporter
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: node update-answers.js
      working-directory: ./test/ci
      env:
        TRANSPORTER: ${{ matrix.transporter }}
    - run: npm test
      env:
        CI: true
    - run: npm run dc:up
      working-directory: ./ci-test
    - run: sleep 10
    - run: docker-compose ps
      working-directory: ./ci-test
    - run: docker-compose logs
      working-directory: ./ci-test
    - run: curl --silent --show-error --fail http://localhost:3000/api/greeter/hello
    - run: curl --silent --show-error --fail http://localhost:3000/api/products
    - run: npm run dc:down
      working-directory: ./ci-test
